version: 2
updates:
  - package-ecosystem: 'github-actions'
    directory: '/'
    schedule:
      interval: 'weekly'
    ignore:
      - dependency-name: 'crate-ci/typos'
    groups:
      nix-actions:
        patterns:
          - 'DeterminateSystems*'
  - package-ecosystem: 'npm'
    directory: '/'
    schedule:
      interval: 'monthly'
    ignore:
      - dependency-name: '@types/*'
        update-types: ['version-update:semver-major']
