name: CI
on:
  push:
    branches: [main]
    paths-ignore:
      - '.github/dependabot.yml'
      - 'LICENSE'
      - '.editorconfig'
      - 'README.md'
      - '.vscode/**'
  pull_request:
    paths-ignore:
      - '.github/dependabot.yml'
      - 'LICENSE'
      - '.editorconfig'
      - 'README.md'
      - '.vscode/**'
jobs:
  build:
    timeout-minutes: 15
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@8ade135a41bc03ea155e62e844d188df1ea18608 # v4.1.0
      - uses: actions/setup-node@0a44ba7841725637a19e28fa30b79a866c81b0a6 # v4.0.4
        with:
          node-version: '20.15.1' # selfup {"extract":"\\d[^']+","replacer":["bash","-c","node --version | tr -d v"]}
          cache: npm
      - run: npm ci --ignore-scripts
      - run: npm run build
      - name: Check no diff for products
        run: git add --intent-to-add . && git diff --exit-code

  test:
    timeout-minutes: 15
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@8ade135a41bc03ea155e62e844d188df1ea18608 # v4.1.0
      - uses: actions/setup-node@0a44ba7841725637a19e28fa30b79a866c81b0a6 # v4.0.4
        with:
          node-version: '20.15.1' # selfup {"extract":"\\d[^']+","replacer":["bash","-c","node --version | tr -d v"]}
          cache: npm
      - run: npm ci --ignore-scripts
      - run: npm test

  typecheck:
    timeout-minutes: 15
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@8ade135a41bc03ea155e62e844d188df1ea18608 # v4.1.0
      - uses: actions/setup-node@0a44ba7841725637a19e28fa30b79a866c81b0a6 # v4.0.4
        with:
          node-version: '20.15.1' # selfup {"extract":"\\d[^']+","replacer":["bash","-c","node --version | tr -d v"]}
          cache: npm
      - run: npm ci --ignore-scripts
      - name: Typecheck
        run: npm run typecheck

  lint:
    timeout-minutes: 15
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@8ade135a41bc03ea155e62e844d188df1ea18608 # v4.1.0
      - uses: denoland/setup-deno@5e01c016a857a4dbb5afe9d0f9733cd472cba985 # v1.5.1
        with:
          deno-version: '1.44.3' # selfup {"extract":"\\d[^']+","replacer":["bash","-c","deno --version | head -n 1 | cut -d ' ' -f 2"]}
      - run: deno lint
