name: Linters
on:
  push:
    branches: [main]
    paths-ignore:
      - 'dist'
      - 'package-lock.json'
  pull_request:
    paths-ignore:
      - 'dist'
      - 'package-lock.json'

jobs:
  dprint:
    timeout-minutes: 15
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: dprint/check@v2.2
        with:
          # Keep same version as *.nix
          dprint-version: '0.36.1'

  typos:
    timeout-minutes: 15
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      # Keep same version as *.nix
      - uses: crate-ci/typos@v1.14.10
