name: Validate itself
on:
  push:
    branches: [main]
    paths-ignore:
      - '.github/dependabot.yml'
      - '.github/workflows/test.yml'
      - '.github/workflows/dependency-review.yml'
      - '.github/workflows/merge-bot-pr.yml'
      - '.github/workflows/codeql-analysis.yml'
      - 'LICENSE'
      - '.editorconfig'
      - 'dprint.json'
      - '.eslintrc.js'
      - 'README.md'
      - '.vscode/**'
  pull_request:
    paths-ignore:
      - '.github/dependabot.yml'
      - '.github/workflows/test.yml'
      - '.github/workflows/dependency-review.yml'
      - '.github/workflows/merge-bot-pr.yml'
      - '.github/workflows/codeql-analysis.yml'
      - 'LICENSE'
      - '.editorconfig'
      - 'dprint.json'
      - '.eslintrc.js'
      - 'README.md'
      - '.vscode/**'

permissions:
  contents: write
  checks: read
  actions: read

jobs:
  validate: # make sure the action works on a clean machine without building
    timeout-minutes: 15
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./
